import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConvexClientProvider } from "@/providers/ConvexClientProvider";
import { Footer } from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vinyl Viper",
  description: "Generated by create next app",
  icons: {
    icon: "/main_logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/main_logo.svg" />
      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-l from-stone-900 to-red-800`}
        className="bg-gradient-to-l from-stone-900 to-red-800"
      >

        <ConvexClientProvider>{children}</ConvexClientProvider>
        <Footer />
      </body>
    </html>
  );
}
